# Generated by Django 4.0 on 2022-11-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tattoo_artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameArtistic', models.CharField(max_length=50)),
                ('departament', models.TextField(max_length=150)),
                ('locaties', models.TextField(max_length=150)),
                ('direction', models.TextField()),
                ('experience', models.IntegerField(max_length=3)),
                ('description', models.TextField(blank=True, default='', max_length=150)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
