# Generated by Django 4.0 on 2022-11-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tattoo_artist',
            old_name='locaties',
            new_name='municipio',
        ),
        migrations.AlterField(
            model_name='tattoo_artist',
            name='description',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tattoo_artist',
            name='direction',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tattoo_artist',
            name='experience',
            field=models.IntegerField(),
        ),
    ]
