# Generated by Django 4.0 on 2022-11-15 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_users_city_remove_users_departament_and_more'),
        ('tatto', '0002_rename_locaties_tattoo_artist_municipio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tattoo_artist',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PerfilProfesional', to='accounts.users'),
            preserve_default=False,
        ),
    ]
