# Generated by Django 4.0 on 2022-11-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatto', '0003_tattoo_artist_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tattoo_artist',
            name='img',
            field=models.TextField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
