# Generated by Django 4.0 on 2022-10-27 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tatoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefcase_artist',
            name='Date_publication',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 9, 26, 54, 979139)),
        ),
    ]
