# Generated by Django 4.0 on 2022-10-27 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tatoo', '0002_alter_briefcase_artist_date_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefcase_artist',
            name='Date_publication',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 14, 35, 58, 13367)),
        ),
    ]
