# Generated by Django 4.0 on 2022-10-27 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tatoo', '0004_alter_briefcase_artist_date_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefcase_artist',
            name='Date_publication',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 16, 39, 49, 655060)),
        ),
    ]
