# Generated by Django 4.0 on 2022-11-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('Id_quotes', models.BigAutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Img', models.ImageField(upload_to='')),
                ('Description', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
