# Generated by Django 4.0 on 2022-11-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='user',
            new_name='userID',
        ),
    ]
