# Generated by Django 4.0 on 2022-11-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_rename_user_quotes_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
